[qt]
GUIEffects=none
KDE\contrast=4
KWinPalette\activeBackground=#1b1b1d
KWinPalette\activeBlend=#1b1b1d
KWinPalette\activeForeground=#edf0f2
KWinPalette\activeTitleBtnBg=#1b1b1d
KWinPalette\frame=#1b1b1d
KWinPalette\inactiveBackground=#1b1b1d
KWinPalette\inactiveBlend=#1b1b1d
KWinPalette\inactiveForeground=#b5b6b6
KWinPalette\inactiveFrame=#1b1b1d
KWinPalette\inactiveTitleBtnBg=#1b1b1d
Palette\active=#fcfdfd, #323236, #39393d, #2d2d30, #101011, #18181a, #fefefe, #ffffff, #fefefe, #1b1b1d, #1b1b1d, #0c0c0c, #eb3131, #fefefe, #1f8cec, #7f8c8d, #1b1b1d, #000000, #27272a, #fcfdfd, #f2f3f3, #eb3131
Palette\disabled=#6a6a6b, #323236, #39393d, #2d2d30, #101011, #18181a, #6a6a6c, #ffffff, #79797c, #1b1b1d, #1b1b1d, #0c0c0c, #1b1b1d, #6a6a6b, #1c4365, #3e4344, #1b1b1d, #000000, #27272a, #fcfdfd, #666768, #1b1b1d
Palette\inactive=#fcfdfd, #323236, #39393d, #2d2d30, #101011, #18181a, #fefefe, #ffffff, #fefefe, #1b1b1d, #1b1b1d, #0c0c0c, #eb3131, #fefefe, #1f8cec, #7f8c8d, #1b1b1d, #000000, #27272a, #fcfdfd, #f2f3f3, #eb3131
font="Noto Sans,10,-1,0,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
