# Noctalia's hand-written config layer, vendored under dotfiles/ and linked
# back into ~/.config/noctalia as OUT-OF-STORE symlinks.
#
# Noctalia reads two layers: every *.toml in ~/.config/noctalia (this one)
# and ~/.local/state/noctalia/settings.toml, which the GUI writes, loads last
# and overrides per key. Only the base layer is vendored — settings.toml
# stays machine-local, holding monitor geometry, wallpaper paths and other
# state that does not travel. So anything changed in Noctalia's own settings
# UI is per machine by construction and never reaches the shared files.
#
# Shared + per-host, like niri's config:
#   dotfiles/noctalia/.config/noctalia/*.toml   shared layer (both hosts)
#   dotfiles/noctalia/hosts/<hostname>/host.toml  per-host layer, linked as
#                                                 ~/.config/noctalia/zz-host.toml
# Noctalia loads the *.toml files in sorted name order and later files win
# (tables merge key by key; arrays and scalars are replaced whole), so the
# per-host link is named zz-host.toml to load after every shared file and
# override it. settings.toml (GUI) still loads last of all. A shared file a
# host must NOT get is disabled host
# side: xdg.configFile."noctalia/<file>".enable = lib.mkForce false in
# modules/hosts/<host>/home.nix.
#
# Linked FILE BY FILE, deliberately. The directory also holds two files this
# module must not own:
#   wallhaven.toml       rendered from a sops secret (wallhaven-secret.nix)
#   user-templates.toml  generated by home-manager (neovim.nix)
# A whole-directory symlink would make both impossible to place.
#
# Because the targets are out-of-store, edits apply without a rebuild and
# land in the checkout as uncommitted changes.
{
  flake.modules.homeManager.noctalia =
    {
      config,
      lib,
      osConfig,
      ...
    }:
    let
      root = "${config.dotfiles.repoPath}/dotfiles/noctalia";
      src = "${root}/.config/noctalia";
      hostDir = "${root}/hosts/${osConfig.networking.hostName}";

      # Relative to the noctalia config dir.
      vendored = [
        "bar.toml" # bar layout + per-widget settings
        "config.toml" # brightness backends (per-output: nostromo-shaped)
        "desktop.toml" # shell, panel, dock, backdrop
        "obsidian.toml" # obsidian theme template registration (nostromo's vault)
        "plugins.toml" # enabled plugins + their settings
        "services.toml" # idle, location, nightlight, weather, calendar
        "theme.toml" # palette, mode, which templates get written
        "Obsidian/obsidian.css" # input template for the obsidian theme
      ];
    in
    {
      xdg.configFile =
        lib.listToAttrs (
          map (rel: {
            name = "noctalia/${rel}";
            value.source = config.lib.file.mkOutOfStoreSymlink "${src}/${rel}";
          }) vendored
        )
        // {
          "noctalia/zz-host.toml".source = config.lib.file.mkOutOfStoreSymlink "${hostDir}/host.toml";
        };
    };
}
