# Noctalia's hand-written config layer, vendored under dotfiles/ and linked
# back into ~/.config/noctalia as OUT-OF-STORE symlinks.
#
# Noctalia reads two layers: every *.toml in ~/.config/noctalia (this one,
# merged alphabetically) and ~/.local/state/noctalia/settings.toml, which the
# GUI writes and which overrides this layer per key. Only the base layer is
# vendored — settings.toml stays machine-local, holding monitor geometry,
# wallpaper paths and other state that does not travel.
#
# Linked FILE BY FILE, deliberately. The directory also holds two files this
# module must not own:
#   wallhaven.toml       rendered from a sops secret (noctalia-wallhaven.nix)
#   user-templates.toml  generated by home-manager (neovim.nix)
# A whole-directory symlink would make both impossible to place.
#
# Because the targets are out-of-store, edits apply without a rebuild and
# land in the checkout as uncommitted changes.
{
  flake.modules.homeManager.noctalia =
    { config, lib, ... }:
    let
      src = "${config.dotfiles.repoPath}/dotfiles/noctalia/.config/noctalia";

      # Relative to the noctalia config dir.
      vendored = [
        "bar.toml" # bar layout + per-widget settings
        "config.toml" # brightness backends (per-output: nostromo-shaped)
        "desktop.toml" # shell, panel, dock, backdrop
        "obsidian.toml" # obsidian theme template registration
        "plugins.toml" # enabled plugins + their settings
        "services.toml" # idle, location, nightlight, weather, calendar
        "theme.toml" # palette, mode, which templates get written
        "Obsidian/obsidian.css" # input template for the obsidian theme
      ];
    in
    {
      xdg.configFile = lib.listToAttrs (
        map (rel: {
          name = "noctalia/${rel}";
          value.source = config.lib.file.mkOutOfStoreSymlink "${src}/${rel}";
        }) vendored
      );
    };
}
