# niri's configuration, vendored under dotfiles/ and linked back into
# ~/.config/niri as OUT-OF-STORE symlinks, so edits apply on niri's next
# config reload without a rebuild and land in the checkout as uncommitted
# changes.
#
# Shared config, per-host fragments, composed by niri's own `include`:
#
#   dotfiles/niri/.config/niri/config.kdl    portable: layout, keybinds,
#                                            window rules. Contains
#                                              include "host.kdl"
#                                              include "noctalia.kdl"
#   dotfiles/niri/hosts/<hostname>/host.kdl      display layout — output
#                                                blocks naming that machine's
#                                                monitors
#   dotfiles/niri/hosts/<hostname>/noctalia.kdl  accent/border colours,
#                                                GENERATED by noctalia's niri
#                                                theme template on every
#                                                palette change
#
# Both per-host files live under hosts/<hostname>/ because both are
# machine-bound: the display layout obviously, and noctalia.kdl because each
# machine regenerates it from its own wallpaper-derived palette — sharing one
# copy would have two hosts overwriting each other on every theme change.
#
# niri resolves `include` relative to the directory of the config file it was
# handed (~/.config/niri), NOT the symlink's target — verified directly, which
# is what makes this split work while config.kdl lives in the repo.
#
# A MISSING include is a fatal parse error: niri rejects the entire config and
# the session will not start. Any host importing the niri feature must have a
# complete dotfiles/niri/hosts/<hostname>/ directory.
{
  flake.modules.homeManager.niri =
    {
      config,
      osConfig,
      ...
    }:
    let
      src = "${config.dotfiles.repoPath}/dotfiles/niri";

      # `osConfig` is the enclosing NixOS configuration — available because
      # home-manager runs as a NixOS module here.
      hostDir = "${src}/hosts/${osConfig.networking.hostName}";

      link = target: { source = config.lib.file.mkOutOfStoreSymlink target; };
    in
    {
      xdg.configFile = {
        "niri/config.kdl" = link "${src}/.config/niri/config.kdl";
        "niri/host.kdl" = link "${hostDir}/host.kdl";
        "niri/noctalia.kdl" = link "${hostDir}/noctalia.kdl";
      };
    };
}
