# niri's configuration, vendored under dotfiles/ and linked back into
# ~/.config/niri as OUT-OF-STORE symlinks, so edits apply on niri's next
# config reload without a rebuild and land in the checkout as uncommitted
# changes.
#
# Split into shared and per-host parts, composed by niri's own `include`:
#
#   dotfiles/niri/.config/niri/config.kdl   shared: layout, keybinds, rules,
#                                           window rules. Contains
#                                             include "host.kdl"
#                                             include "noctalia.kdl"
#   dotfiles/niri/hosts/<hostname>.kdl      per-host: display layout (output
#                                           blocks naming that machine's
#                                           monitors)
#   dotfiles/niri/.config/niri/noctalia.kdl GENERATED by noctalia's niri theme
#                                           template on every palette change
#
# niri resolves `include` relative to the directory of the config file it was
# handed (~/.config/niri), NOT the symlink's target — verified directly, which
# is what makes this split work while config.kdl lives in the repo.
#
# A MISSING include is a fatal parse error: niri rejects the entire config and
# the session will not start. Every host importing the niri feature must have
# a dotfiles/niri/hosts/<hostname>.kdl, or this links to nothing.
#
# noctalia.kdl is shared rather than per-host. Correct while one machine runs
# this stack; if a second one ever does, the two will fight over the file on
# every theme change and it should move under hosts/ too.
{
  flake.modules.homeManager.niri =
    {
      config,
      osConfig,
      ...
    }:
    let
      src = "${config.dotfiles.repoPath}/dotfiles/niri";
      link = target: { source = config.lib.file.mkOutOfStoreSymlink target; };
    in
    {
      xdg.configFile = {
        "niri/config.kdl" = link "${src}/.config/niri/config.kdl";
        "niri/noctalia.kdl" = link "${src}/.config/niri/noctalia.kdl";

        # `osConfig` is the enclosing NixOS configuration — available because
        # home-manager runs as a NixOS module here. Selects this machine's
        # display layout by hostname.
        "niri/host.kdl" = link "${src}/hosts/${osConfig.networking.hostName}.kdl";
      };
    };
}
