# niri's configuration, vendored under dotfiles/ and linked back into
# ~/.config/niri as OUT-OF-STORE symlinks, so edits apply on niri's next
# config reload without a rebuild and land in the checkout as uncommitted
# changes.
#
# Two files, with different authorship:
#
#   config.kdl    hand-written. Ends with `include "noctalia.kdl"`.
#                 Contains per-output blocks naming this machine's displays
#                 (eDP-1, and two specific external monitors) — niri ignores
#                 blocks for absent outputs, so it is portable, but it is
#                 nostromo-shaped and worth splitting if another host ever
#                 runs niri.
#
#   noctalia.kdl  GENERATED by noctalia's `niri` theme template on every
#                 theme change (it carries the accent/border colours).
#                 Vendored anyway because config.kdl's include would fail
#                 without it. Verified empirically that noctalia rewrites it
#                 *through* the symlink rather than replacing it, so the link
#                 survives and theme changes show up as a dirty tree. Expect
#                 churn here on every palette change.
#
# Linked file by file for consistency with the noctalia feature, and so that
# anything else landing in ~/.config/niri stays unmanaged rather than being
# swallowed by a directory-level link.
{
  flake.modules.homeManager.niri =
    { config, lib, ... }:
    let
      src = "${config.dotfiles.repoPath}/dotfiles/niri/.config/niri";
      vendored = [
        "config.kdl"
        "noctalia.kdl"
      ];
    in
    {
      xdg.configFile = lib.listToAttrs (
        map (rel: {
          name = "niri/${rel}";
          value.source = config.lib.file.mkOutOfStoreSymlink "${src}/${rel}";
        }) vendored
      );
    };
}
