set -g default-command "${SHELL}"
#set prefix to Ctrl-A
set -g prefix C-a
#unbid default prefix
unbind C-b
#send Ctrl-A to applications by pressing it twice
bind C-a send-prefix

#enable mouse
set -g mouse

#customize status bar colors
##status bar bg
set -g status-bg cyan
##inactive
set -g window-status-style bg=yellow
##active
set -g window-status-current-style bg=red,fg=white

#vi style keys
setw -g mode-keys vi

#set larger history
set-option -g history-limit 5000

#use backtip to switch to marked pane
bind \` switch-client -t'{marked}'

#change pane split keys to | and -
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"
