[brightness]
enable_ddcutil     = true
ignore_mmids       = []     # e.g. ["ACI-ROG_PG279Q-10220"] - skip in all ddcutil commands
minimum_brightness = 0.2    # never let brightness drop below this floor (0.0 to 1.0)
sync_all_monitors = true   # if set to true, makes every display have the same brightness

[brightness.monitor.eDP-1]
backend = "backlight"   # auto | none | backlight | ddcutil
backlight_device = "amdgpu_bl1"   # explicit sysfs device name or path

[brightness.monitor.DP-1]
backend = "auto"
[brightness.monitor.DP-2]
backend = "auto"
